// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubjectsAndDistrictsDbContext;

namespace SubjectsAndDistrictsDbContext.Migrations
{
    [DbContext(typeof(SubjectsAndDistrictsContext))]
    [Migration("20211203183300_OnDelete")]
    partial class OnDelete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SubjectsAndDistrictsDbContext.Model.DTO.DistrictDbDTO", b =>
                {
                    b.Property<long>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("code")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("District");
                });

            modelBuilder.Entity("SubjectsAndDistrictsDbContext.Model.DTO.SubjectDbDTO", b =>
                {
                    b.Property<long>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("code")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("AdminCenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("admin_center_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<double>("Population")
                        .HasColumnType("float(53)")
                        .HasColumnName("population");

                    b.Property<double>("Square")
                        .HasColumnType("float(53)")
                        .HasColumnName("square");

                    b.Property<long>("district_code")
                        .HasColumnType("bigint");

                    b.HasKey("Code");

                    b.HasIndex("district_code");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("SubjectsAndDistrictsDbContext.Model.DTO.SubjectDbDTO", b =>
                {
                    b.HasOne("SubjectsAndDistrictsDbContext.Model.DTO.DistrictDbDTO", "District")
                        .WithMany("Subjects")
                        .HasForeignKey("district_code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("SubjectsAndDistrictsDbContext.Model.DTO.DistrictDbDTO", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
